name: 'PR Check Status Notifier JS'
description: 'Monitors PR checks and notifies when all checks (except specified ones) have passed'
author: 'Tim Fall'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  excluded-checks:
    description: 'Comma-separated list of check names to exclude'
    required: false
    default: 'notify-check'
  notification-message:
    description: 'Custom notification message (use {user} for PR owner mention)'
    required: false
    default: '@{user} All checks have passed! ✅\nThis PR is ready!'
  poll-interval:
    description: 'Polling interval in seconds'
    required: false
    default: '30'
  timeout:
    description: 'Maximum time to wait in minutes'
    required: false
    default: '30'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'green'