name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Update major version tag
        run: |
          major_version=v$(echo "${{ github.ref_name }}" | cut -d. -f1 | sed 's/v//')
          git tag -f "${major_version}" refs/tags/${{ github.ref_name }}
          git push -f origin "${major_version}"